java.compatibility=8
kotlin.compatibility=2.1.20

kdoc.olderVersions=
kdoc.artifactId=kdoc
kdoc.projects=*

git.snapshots=main

pom.groupId=com.apollographql.adapters
pom.version=0.7.1-SNAPSHOT
pom.description=Datetime, BigDecimal and other adapters for Apollo Kotlin
pom.vcsUrl=https://github.com/apollographql/apollo-kotlin-adapters
pom.developer=apollo-kotlin-adapters authors
pom.license=MIT
