[versions]
apollo = "4.0.0"

[libraries]
apollo-api = { module = "com.apollographql.apollo:apollo-api", version.ref = "apollo" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.5.0"
