[libraries]
apollo-api = "com.apollographql.apollo:apollo-api:4.0.0-rc.1"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.5.0"
